import { Package, Smartphone, ShoppingCart, Users, CreditCard, Tag, Share2, Wallet, RefreshCcw, Bell, Languages, ShieldCheck, MapPin, Truck, Settings, Image as ImageIcon, LayoutDashboard, Layers } from "lucide-react";

export const CATEGORIES = [
  { id: "snacks", name: "Snacks & Munchies", count: 120 },
  { id: "cosmetics", name: "Beauty & Cosmetics", count: 85 },
  { id: "beverages", name: "Beverages", count: 64 },
  { id: "household", name: "Household Essentials", count: 92 },
  { id: "personal-care", name: "Personal Care", count: 78 },
];

export const PRODUCTS = [
  {
    id: "p1",
    name: "Classic Salted Chips",
    brand: "Lays",
    category: "snacks",
    subCategory: "Chips & Crisps",
    mrp: 35,
    price: 30,
    unit: "50g",
    stock: 500,
    description: "Crispy and delicious classic salted potato chips made from high-quality potatoes.",
    sku: "SNK-LYS-001",
    image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80",
    status: "Active",
  },
  {
    id: "p2",
    name: "Moisturizing Cream",
    brand: "Nivea",
    category: "cosmetics",
    subCategory: "Skincare",
    mrp: 180,
    price: 150,
    unit: "100ml",
    stock: 200,
    description: "Enriched with skin-natural moisturizers for long-lasting hydration.",
    sku: "COS-NIV-002",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
    status: "Active",
  },
  {
    id: "p3",
    name: "Energy Drink",
    brand: "Red Bull",
    category: "beverages",
    subCategory: "Cold Drinks",
    mrp: 60,
    price: 50,
    unit: "250ml",
    stock: 350,
    description: "Revitalizes body and mind. High caffeine content.",
    sku: "BEV-RB-003",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
    status: "Active",
  },
  {
    id: "p4",
    name: "Detergent Liquid",
    brand: "Surf Excel",
    category: "household",
    subCategory: "Laundry",
    mrp: 300,
    price: 250,
    unit: "1L",
    stock: 120,
    description: "Tough on stains, gentle on fabrics. Advance formula for superior cleaning.",
    sku: "HOU-SE-004",
    image: "https://images.unsplash.com/photo-1584622781564-1d9876a13d00?w=400&q=80",
    status: "Low Stock",
  },
];


export const USERS = [
  {
    id: "u1",
    name: "Rahul Sharma",
    phone: "+91 9876543210",
    email: "rahul@example.com",
    status: "Active",
    orders: 12,
    joined: "2023-10-15",
    addresses: ["H.No 123, Sector 4, Hyderabad"],
  },
  {
    id: "u2",
    name: "Anjali Rao",
    phone: "+91 9123456789",
    email: "anjali@example.com",
    status: "Blocked",
    orders: 0,
    joined: "2024-01-20",
    addresses: ["Flat 502, Pearl Residency, Bangalore"],
  },
  {
    id: "u3",
    name: "Vijay Kumar",
    phone: "+91 8888777766",
    email: "vijay@example.com",
    status: "Active",
    orders: 5,
    joined: "2024-02-05",
    addresses: ["12-A, Jubilee Hills, Hyderabad"],
  },
];

export const ORDERS = [
  {
    id: "ORD-7721",
    user: "Rahul Sharma",
    items: 4,
    total: 850,
    status: "Delivered",
    date: "2024-04-10",
    payment: "Paid (UPI)",
  },
  {
    id: "ORD-7722",
    user: "Vijay Kumar",
    items: 2,
    total: 320,
    status: "Shipped",
    date: "2024-04-12",
    payment: "COD",
  },
  {
    id: "ORD-7723",
    user: "Priya Singh",
    items: 1,
    total: 1299,
    status: "Processing",
    date: "2024-04-14",
    payment: "Paid (Card)",
  },
];

export const ANALYTICS = {
  salesData: [
    { name: "Mon", total: 4500 },
    { name: "Tue", total: 5200 },
    { name: "Wed", total: 4800 },
    { name: "Thu", total: 6100 },
    { name: "Fri", total: 5900 },
    { name: "Sat", total: 7200 },
    { name: "Sun", total: 6800 },
  ],
  stats: [
    { label: "Total Revenue", value: "₹4,25,000", change: "+12.5%", icon: CreditCard },
    { label: "Total Orders", value: "1,250", change: "+8.2%", icon: ShoppingCart },
    { label: "Active Users", value: "842", change: "+15.3%", icon: Users },
    { label: "Conversion Rate", value: "3.4%", change: "-1.2%", icon: RefreshCcw },
  ],
};

export const MENU_ITEMS = [
  { icon: Smartphone, label: "Dashboard", href: "/" },
  { icon: Users, label: "Users", href: "/users" },
  { icon: ShoppingCart, label: "Products", href: "/products" },
  { icon: CreditCard, label: "Orders", href: "/orders" },
  { icon: Tag, label: "Coupons", href: "/coupons" },
  { icon: Layers, label: "Categories", href: "/categories" },
  { icon: ImageIcon, label: "Image Gallery", href: "/gallery" },
  { icon: ImageIcon, label: "Banners", href: "/banners" },
  { icon: Smartphone, label: "Home Offers", href: "/home-offers" },
  { icon: LayoutDashboard, label: "Brands", href: "/brands" },
  { icon: Share2, label: "Referrals", href: "/referrals" },
  { icon: Wallet, label: "Wallet", href: "/wallet" },
  { icon: RefreshCcw, label: "Refunds", href: "/refunds" },
  { icon: Bell, label: "Notifications", href: "/notifications" },
  { icon: Languages, label: "Languages", href: "/languages" },
  { icon: ShieldCheck, label: "Sub-Admins", href: "/team" },
  { icon: Truck, label: "Shipping", href: "/shipping" },
  { icon: Settings, label: "Settings", href: "/settings" },
];
